### ISSUE TITLE
Source code update

### ISSUE THREAD

**Issue by tonysprenk** [dayanch96/YTLite#109]
Would it be possible to have the source code updated so that we can enjoy the new features and fixes when building with YTLitePlus? Thank you for the great tweak!

**Comment by encode42** [comment]
Has the project effectively gone closed source? I started using this over the other YouTube enhancement tweaks since it was fully open source, allowing me to properly trust it with my account. It'd be quite unfortunate if this has changed.

Will source commits be staggered? Will I need to look for an alternative? Is this just a one-time deal? This has been by-far the most stable YouTube tweak I've used, so it'd be a shame to watch it go downhill.

**Comment by dayanch96** [comment]
You can thank those who steal the code, dont gives credits and releases it as their own. The tweak was open-source in the hope that others will also contribute but not steal it. _We have to appreciate what we have before we lose it_

As for trust, that's everyone's own choice

**Comment by encode42** [comment]
Understandable :+1:

I completely get where you're coming from. I've seen how other projects treat your work. It's unfortunate how the act of giving credit is often stigmatized in the open-source community.

As somebody who has dealt with a very similar situation in a different corner of open-source, I'm sorry you have to deal with these projects that market your hard work as their own. I still hope that some day, these issues are resolved, and the project can return to being fully open-source!

**Comment by Balackburn** [comment]
Hi @dayanch96,

I don't know if you're talking about YTLitePlus but if you are I'm really desolate to hear that you're feeling ripped off. I started the YTLitePlus project on my own free time, not as a developer but just as an excited user who wanted to build the best YouTube .ipa for his own personal use. My intention was never to pass it off as my own or steal your code - I genuinely thought that by giving you credit and building on the open-source foundation, I was contributing positively to the community.

However, I can see now that the way I implemented and promoted the project may have come across as disrespectful or deceptive and I didn't gave you enough credit, I must admit. I should have been more proactive in communicating with you directly, rather than just assuming the credit would be enough. The website, Reddit posts, and other promotion were an attempt to grow the user base as I felt like it was the best AIO tweaked Youtube avaible, but I can understand how that might have frustrated you as the original creator and feeling like I was taking credit for your work. Also, all the visuals I created for YTLitePlus were just an attempt to make things look better and more "professional", same for making it an organization.

If you're open to it, I'd be happy to find a way to continue the project that properly respects your work and contributions. I'm willing to make any changes you see fit, whether that's the name, credits, or anything else.
I really didn't have any bad intentions, you could have contacted me to tell me what was wrong.
As a user of your work, I have the utmost respect for the passion and hard work that goes into creating projects like this. I'm truly sorry for any pain I've caused you, and I hope we can find a resolution that works for both of us. Please let me know how I can make this right. 

If you're talking about someone else, my comment still stands.
